[package]
name = "hiai-rs-sys"
version.workspace = true
edition.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true
description = "Raw FFI bindings to Huawei HiAI (CANN) DDK"
readme = "../README.md"
links = "hiai"
keywords = ["ascend", "cann", "hiai", "npu", "ffi"]
categories = ["external-ffi-bindings", "hardware-support"]

[build-dependencies]
bindgen = "0.72"
cc = "1.0"
